### ISSUE TITLE
Add Code of Conduct page

### ISSUE THREAD

**Issue by mateoclarke** [La-Murga-de-Austin/lmda-eleventy-netlify-cms#4]
https://docs.google.com/forms/d/e/1FAIpQLSfU6KRY8B99CLw4_pMM8tq1gsi7aAbZhAmAw1SP5-9gWo6yqA/viewform

**Comment by wileykoepp** [comment]
Wiley didn't realize he'd created a duplicate issue, which has been completed: https://github.com/La-Murga-de-Austin/lmda-eleventy-netlify-cms/issues/17
